### ISSUE TITLE
Who is the original author that needs to be creditted?

### ISSUE THREAD

**Issue by kvz** [jnv/ansible-role-unattended-upgrades#22]
Hi, I'm including this role in another open source project, and would like to be respectful of licensing. I'm having a bit of trouble with the attribution in this case:

```
$ grep -i copyright /Users/kvz/code/frey/roles/unattended-upgrades/v1.2.0/LICENSE
 Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
  We protect your rights with two steps: (1) copyright the software, and
a notice placed by the copyright holder saying it may be distributed
means either the Program or any derivative work under copyright law:
copyright notice and disclaimer of warranty; keep intact all the
    announcement including an appropriate copyright notice and a
certain countries either by patents or by copyrighted interfaces, the
original copyright holder who places the Program under this License
to ask for permission.  For software which is copyrighted by the Free
OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR
the "copyright" line and a pointer to where the full notice is found.
    Copyright (C) <year>  <name of author>
    Gnomovision version 69, Copyright (C) year name of author
school, if any, to sign a "copyright disclaimer" for the program, if
  Yoyodyne, Inc., hereby disclaims all copyright interest in the program
```

Who should be credited here? It seems the license still holds `<name of author>`

**Comment by fwilhe** [comment]
I guess [this](https://github.com/jnv/ansible-role-unattended-upgrades/blob/master/meta/main.yml#L3) is the answer, isn't it?

**Comment by jnv** [comment]
Yeah, the thing is, I am the author of the role, but most parts (especially in the configuration) are copied from the unattended-upgrades package. That's why I went with the GPL 2 license, which is the license of the original package.

So feel free to attribute either me, authors of Unattended Upgrades or both.

As for the LICENSE file, AFAIK the part you mentioned is just an example of the license usage, I don't think the license file needs to be changed (but perhaps I am wrong).
