### ISSUE TITLE
would this work on 16.04 ? 

### ISSUE THREAD

**Issue by adi2909** [jnv/ansible-role-unattended-upgrades#30]
Hi, 

I want to upgrade our OS from 15.10 (which runs the unattended upgrades beautifully) to 16.04...I upgraded the ami to 16.04 using packer and it didnt throw out any error but when i log on to a test machine i get the following error as soon as you run an apt-get update: 

N: Ignoring file '50unattended-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension

**Comment by jnv** [comment]
Yeah, from what I gathered, ucf-dist files are backup files generated during distribution upgrade. Apt complains about an extra file, but otherwise it should work normally. You can remove the file. Rerun the role to put your configuration into 50unattended-upgrades file.

See http://askubuntu.com/questions/829370/n-ignoring-file-50unattended-upgrades-ucf-dist-in-directory-etc-apt-apt-con
