### ISSUE TITLE
Random reboots on Ubuntu 16.04

### ISSUE THREAD

**Issue by dnmvisser** [jnv/ansible-role-unattended-upgrades#35]
Apparently all `systemd` systems are suffering from this:

http://askubuntu.com/questions/824718/ubuntu-16-04-unattended-upgrades-runs-at-random-times

Not entire sure but it seems appropriate to add the timer override to this role, so there is predictable behavior.

**Comment by jnv** [comment]
Well, this is definitely an issue which should be fixed upstream in apt package, see e.g. here: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1615482

IMO override for this is within scope of some apt / systemd role, since this affects all apt-daily tasks, not just unattended-upgrades. I would be happy to add warning and guidelines to fix this behaviour into the documentation though.

**Comment by jnv** [comment]
According to Launchpad this issue was fixed in Zesty. I will close this, but let me know if you'd like to add some info for LTS releases.
