### ISSUE TITLE
Erroneously reports failure on Debian 9 "Stretch"

### ISSUE THREAD

**Issue by sampablokuper** [jnv/ansible-role-unattended-upgrades#44]
Using v1.4.0 of this module, with both `reboot-notifier` and `update-notifier` installed on the target host, I get:

```
TASK [jnv.unattended-upgrades : install update-notifier-common] *******************
fatal: [my_host]: FAILED! => {"changed": false, "msg": "No package matching 'update-notifier-common' is available"}
...ignoring
```

**Comment by sampablokuper** [comment]
Closing this issue, as I think it makes more sense to track it [here](https://github.com/jnv/ansible-role-unattended-upgrades/issues/6#issuecomment-361236301), but feel free to re-open this issue report if you would prefer. Thanks :)

**Comment by sampablokuper** [comment]
Re-opening, as I will file a PR shortly to fix this.

**Comment by jnv** [comment]
Thanks for your report and PR, @sampablokuper. I have decided to handle the error differently, because this also affects Ubuntu and other Debian derivatives. By setting `failed_when: false` the task should fail silently. I will remove the task completely in the next major version of the role, as support for Debian 7 (oldoldstable) expires on May 31st.
