### ISSUE TITLE
Default configuration should use AllowedOrigins in Ubuntu

### ISSUE THREAD

**Issue by Chithrak07** [jnv/ansible-role-unattended-upgrades#82]
The current jnv role is applying old syntax to new machines.

The section `origins-pattern `  seems to have changed to `allowed-origins` as of 18.04.

**Comment by jnv** [comment]
Thanks for the report. It seems the usage of OriginsPattern vs. AllowedOrigins is distribution-specific, compare the upstream configuration for [Debian](https://github.com/mvo5/unattended-upgrades/blob/master/data/50unattended-upgrades.Debian) vs. [Ubuntu](https://github.com/mvo5/unattended-upgrades/blob/master/data/50unattended-upgrades.Ubuntu). My understanding of these choices is that OriginsPattern is more powerful and should be backwards compatible with AllowedOrigins, but I can be mistaken.

Anyway, feel free to submit a fix to use AllowedOrigins instead of OriginsPattern on Ubuntu.

**Comment by dale-c-anderson** [comment]
@jnv that actually explains a lot. 

Any chance https://github.com/jnv/ansible-role-unattended-upgrades/pull/66 is going to get merged in soon? If not, we'll fork form  Consensus's role until it all makes it to master in yours.

**Comment by jnv** [comment]
I am closing this issue since this role has been deprecated. Feel free to suggest alternatives in #98.
